config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dev_ex#index'

  get 'ref', to: 'dev_ex#ref'

  get 'description', to: 'dev_ex#description'

  get 'start_date', to: 'dev_ex#start_date'
end

app/controllers/dev_ex_controller.rb
class DevExController < ApplicationController
  include DevExParseParams
  include DevExApplyParams

  # При фильтрации нужно учитывать допустимые операторы для полей
  # Для группировки достаточно реализовать фильтры

  def index
    respond_to do |format|
      format.json do
        list_params = all_params_parse(params)
        scope = DevExData
        if list_params.dig(:group)
          # Фильтрация данных
          scope = search_scope(scope, list_params)
          scope = filter_scope(scope, list_params)
          # Подсчет итогов
          total_summary = total_summary_data(scope, list_params) if list_params.dig(:totals, :total_summary)
          total_count = calc_totals(scope, list_params) if list_params.dig(:totals, :total_count)
          # Данные с группировкой
          res = group_data(scope, list_params)
          top_group_count = res.count
          # Форматирование результата
          data = { data: res }
          data['groupCount'] = top_group_count if list_params.dig(:totals, :group_count)
          data['summary'] = total_summary if list_params.dig(:totals, :total_summary)
          data['totalCount'] = total_count if list_params.dig(:totals, :total_count)
          render json: data
        else
          # Фильтрация данных
          scope = search_scope(scope, list_params)
          scope = filter_scope(scope, list_params)
           # Подсчет итогов
          total_summary = total_summary_data(scope, list_params) if list_params.dig(:totals, :total_summary)
          total_count = calc_totals(scope, list_params) if list_params.dig(:totals, :total_count)
          # Сортировка и пагинаци
          scope = sort_scope(scope, list_params)
          scope = paginate_scope(scope, list_params)
          # Данные
          res = scope.all
          # Форматирование результата
          data = {data: res}
          data['summary'] = total_summary if list_params.dig(:totals, :total_summary)
          data['totalCount'] = total_count if list_params.dig(:totals, :total_count)
          render json: data
        end
      end
      format.html do
      end
    end
  end

  def ref
    @report_data = DevExRef # search_params_parse(DevExRef)
    total_count =  0 # @report_data.count()
    @report_data = @report_data.order('name asc')
                      .offset(params[:skip])
                      .limit(params[:take])
    render json: {data: serialize_ref(@report_data), totalCount: total_count }
  end

  def description
    @report_data = DevExData
    total_count =  0 # @report_data.count()
    @report_data = @report_data.select(:description).distinct.order('description asc')
                      .offset(params[:skip])
                      .limit(params[:take])
    render json: {data: serialize_description(@report_data), totalCount: total_count }
  end

  def start_date
    @report_data = DevExData
    total_count =  0 # @report_data.count()
    @report_data = @report_data.select(:start_date).distinct.order('start_date asc')
                      .offset(params[:skip])
                      .limit(params[:take])
    render json: {data: serialize_start_date(@report_data), totalCount: total_count }
  end

  private

  def filter(scope)

    return scope
  end

  # "filter", ok
  # "group",
  # "groupSummary",
  # "parentIds",
  # "requireGroupCount", ok
  # "requireTotalCount", ok
  # "searchExpr", ok
  # "searchOperation", ok
  # "searchValue", ok
  # "select",
  # "sort", ok
  # "skip", ok
  # "take", ok
  # "totalSummary",
  # "userData"


  # Для каждой модели свой сериализатор
  def serialize_ref(data)
    data.map{|item| {text: item.name, value: item.id}}
  end

  def serialize_description(data)
    data.map{|item| {text: item.description, value: item.description}}
  end

  def serialize_start_date(data)
    data.map{|item| {text: item.start_date, value: item.start_date}}
  end
end

app/views/dev_ex/_columns.js.erb
function gridColumns(){
 return [{dataField: 'description',
          allowGrouping: true,
          allowSorting: true,
           headerFilter: {
            dataSource: descriptionDataSource(),
            allowSearch: true
           }
        },
         {dataField:'ref1_id',
           allowGrouping: true,
           allowSorting: true,
           headerFilter: {
            dataSource: refDataSource(),
            allowSearch: true
           }
         },
         // {dataField:'ref2_id',
         //  allowGrouping: true,
         //  allowSorting: true,
         //  headerFilter: {
         //    allowSearch: true
         //  },
         //  lookup: {
         //      dataSource: refDataSource(),
         //      displayExpr: 'text',
         //      valueExpr: 'value'
         //  },
         //  calculateSortValue: function (data) {
         //      const value = this.calculateCellValue(data);
         //      return this.lookup.calculateCellValue(value);
         //  }
         // },
         {dataField:'start_date',
          allowGrouping: true,
          allowSorting: true,
          allowSearch: false,
           headerFilter: {
            dataSource: startDateDataSource(),
            allowSearch: true
           }
         },
        ]
}

function totalItems() {
  return [
    {}
  ]
}

app/views/dev_ex/_datasources.js.erb
function gridDataSource(){
  const SERVICE_URL = '<%= root_path %>'
  const dataSource = new DevExpress.data.CustomStore(
    {
      key: "id",
      loadMode:  'processed', //'raw',
      load: loadStandart(SERVICE_URL, gridResolveBuilder),
            // Needed to process selected value(s) in the SelectBox, Lookup, Autocomplete, and DropDownBox
            // byKey: function(key) {
            //     var d = new $.Deferred();
            //     $.get('https://mydomain.com/MyDataService?id=' + key)
            //         .done(function(result) {
            //             d.resolve(result);
            //         });
            //     return d.promise();
            // }
      // Если loadMode: 'processed' то нужно реализовать totalCount и byKey
    }
  )

  return dataSource
}

function refDataSource(){
  const SERVICE_URL = '<%= ref_path %>'
  const dataSource = new DevExpress.data.CustomStore(
    {
      key: "value",
      loadMode: 'processed', //'raw',
      load: loadStandart(SERVICE_URL, refResolveBuilder),
    }
  )

  return dataSource
}

function descriptionDataSource(){
  const SERVICE_URL = '<%= description_path %>'
  const dataSource = new DevExpress.data.CustomStore(
    {
      key: "value",
      loadMode: 'processed', //'raw',
      load: loadStandart(SERVICE_URL, refResolveBuilder),
    }
  )

  return dataSource
}

function startDateDataSource(){
  const SERVICE_URL = '<%= start_date_path %>'
  const dataSource = new DevExpress.data.CustomStore(
    {
      key: "value",
      loadMode: 'processed', //'raw',
      load: loadStandart(SERVICE_URL, refResolveBuilder),
    }
  )

  return dataSource
}

function isNotEmpty(value) {
  return value !== undefined && value !== null && value !== '';
}

function buildParamsFromLoadOptions(loadOptions) {
  var params = {};

  [
      "filter",
      "group",
      "groupSummary",
      "parentIds",
      "requireGroupCount",
      "requireTotalCount",
      "searchExpr",
      "searchOperation",
      "searchValue",
      "select",
      "sort",
      "skip",
      "take",
      "totalSummary",
      "userData"
  ].forEach(function(i) {
      if(i in loadOptions && isNotEmpty(loadOptions[i])) {
          params[i] = JSON.stringify(loadOptions[i]);
      }
  });
  return params
}

function loadStandart(serviceUrl, buildResolve) {
  return function(loadOptions) {
        var d = $.Deferred();
        const params = buildParamsFromLoadOptions(loadOptions)
        console.log('PARAMS')
        console.log(params)
        console.log(serviceUrl)

        $.ajax({
          url: serviceUrl,
          method: 'get',
          dataType: 'json',
          contentType: "application/json; charset=utf-8",
          data: params,
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          timeout: 5000,
          success(response){
              console.log('RESPONSE')
              console.log(response)
              buildResolve(d, response)
          },
          error(result) {
            console.log('error')
            d.reject('Ошибка загрузки данных с сервера');
          },
        });

        return d.promise();
    }
}

function gridResolveBuilder(d, response) {
  d.resolve(
            response.data,
            {
                totalCount: response.totalCount,
                summary: response.summary,
                groupCount: response.groupCount,
            }
          )
}

function refResolveBuilder(d, response) {
  d.resolve(
            response.data,
            {
                totalCount: response.totalCount,
                summary: response.summary,
                groupCount: response.groupCount
            }
          )

}

app/views/dev_ex/_index.js.erb
// // Локализация компонентов отчета
DevExpress.localization.locale('ru');

<%= render partial: 'datasources', formats: [:js] %>
<%= render partial: 'columns', formats: [:js] %>


const grid = $('#grid').dxDataGrid({
    paging: { enabled: true },
    dataSource: gridDataSource(),
    selection: {
      mode: 'single',
    },
    remoteOperations: {
     paging: true,
     filtering: true,
     sorting: true,
     grouping: true, //!
     summary: true, //!
     groupPaging: true, //!
    },
    hoverStateEnabled: true,
    columns: gridColumns(),
    groupPanel: {visible: true},
    headerFilter: {allowSearch: true, visible: false},
    filterPanel: {visible: true},
    filterRow: {visible: true},
    wordWrapEnabled: true,
    allowColumnReordering: true,
    allowColumnResizing: true,
    // columnAutoWidth: true,
    showBorders: true,
    width: 'auto',
    searchPanel: { visible: true},
    sorting: {
      mode: 'multiple',
    },
    columnChooser: {
      enabled: false,
    },
    columnFixing: {
      enabled: false,
    },
    selection: {
      mode: 'single',
    },
    showBorders: true,
    scrolling: {
      mode: 'standard',
    },
    headerFilter: {
      visible: true,
    },
    summary: {
     totalItems: [
          { name: "ref1_id_val", column: "ref1_id", summaryType: "sum",  showInColumn: "ref1_id", },
          { name: "ref1_id_val_avg", column: "ref1_id", summaryType: "avg", showInColumn: "start_date", },
      ],
     groupItems: [
          { name: "ref1_id_val", column: "ref1_id", summaryType: "sum",  showInColumn: "ref1_id", },
          { name: "ref1_id_val_avg", column: "ref1_id", summaryType: "avg", showInColumn: "start_date", },
      ],
    }
  }
).dxDataGrid('instance')

app/views/dev_ex/index.html.erb
<h1>TEST GRID</h1>

<div class="dx-viewport">
  <div id='grid'></div>
</div>

<script type="text/javascript">
  $(() => {
      <%= render partial: 'index', formats: [:js] %>
  })
</script>